name: callkit_new_incoming
description: Flutter Callkit Incoming to show callkit screen in your Flutter app.
version: 3.0.1
homepage: https://github.com/kostasoft/callkit_new_incoming


environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=1.20.0"


dependencies:
  flutter:
    sdk: flutter
  json_annotation: any

dev_dependencies:
  build_runner: any
  flutter_lints: any
  flutter_test:
    sdk: flutter
  json_serializable: any

flutter:

  plugin:
    platforms:
      android:
        package: com.hiennv.flutter_callkit_incoming
        pluginClass: FlutterCallkitIncomingPlugin
